# CMake generated Testfile for 
# Source directory: /home/gwangmu/Projects/libsarus/test
# Build directory: /home/gwangmu/Projects/libsarus/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(libsarus_CLIArguments "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_CLIArguments")
set_tests_properties(libsarus_CLIArguments PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;6;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;6;add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_Error "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_Error")
set_tests_properties(libsarus_Error PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;6;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;7;add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_Flock "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_Flock")
set_tests_properties(libsarus_Flock PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;6;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;8;add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_HookUtility "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_HookUtility")
set_tests_properties(libsarus_HookUtility PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;6;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;9;add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_Lockfile "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_Lockfile")
set_tests_properties(libsarus_Lockfile PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;6;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;10;add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_Logger "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_Logger")
set_tests_properties(libsarus_Logger PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;6;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;11;add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_MountParser "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_MountParser")
set_tests_properties(libsarus_MountParser PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;6;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;12;add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_PasswdDB "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_PasswdDB")
set_tests_properties(libsarus_PasswdDB PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;6;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;13;add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_DeviceMount_AsRoot "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_DeviceMount_AsRoot")
set_tests_properties(libsarus_DeviceMount_AsRoot PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;10;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;14;add_unit_test_as_root;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_DeviceParser_AsRoot "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_DeviceParser_AsRoot")
set_tests_properties(libsarus_DeviceParser_AsRoot PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;10;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;15;add_unit_test_as_root;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_MountUtility_AsRoot "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_MountUtility_AsRoot")
set_tests_properties(libsarus_MountUtility_AsRoot PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;10;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;16;add_unit_test_as_root;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_Mount_AsRoot "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_Mount_AsRoot")
set_tests_properties(libsarus_Mount_AsRoot PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;10;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;17;add_unit_test_as_root;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
add_test(libsarus_Utility_AsRoot "bash" "-c" "cd /home/gwangmu/Projects/libsarus/test && /home/gwangmu/Projects/libsarus/test/test_libsarus_Utility_AsRoot")
set_tests_properties(libsarus_Utility_AsRoot PROPERTIES  _BACKTRACE_TRIPLES "/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;32;add_test;/home/gwangmu/Projects/libsarus/cmake/modules/add_unit_test.cmake;10;_add_unit_test;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;18;add_unit_test_as_root;/home/gwangmu/Projects/libsarus/test/CMakeLists.txt;0;")
subdirs("aux")
