#!/bin/bash
BUILD_DIR=$PWD/build
TOOLCHAIN_FILE=gcc.cmake
BUILD_TYPE=Debug
INSTALL_DIR=$PWD/build/install

cmake -DCMAKE_TOOLCHAIN_FILE=$BUILD_DIR/../cmake/toolchain_files/$TOOLCHAIN_FILE \
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
      -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
      -B $BUILD_DIR -S .
