inputs:
  artifact-tag:
    description: "Artifact tag"
  github_token:
    description: "GitHub token"

runs:
  using: "composite"
  steps:
    - name: Initialize git repository
      shell: bash
      run: git config --global --add safe.directory '*'

    - name: Download build
      uses: actions/download-artifact@v4
      with:
        name: build-${{ inputs.artifact-tag }}
        path: build

    - name: Rename artifact
      shell: bash
      run: |
        mv build/src/libsarus.a build/src/libsarus-${ARCH}-${TAG}.a
        mv build/src/libsarus.so build/src/libsarus-${ARCH}-${TAG}.so
      env:
        ARCH: "x86_64"
        TAG: ${{ inputs.artifact-tag }}

    - name: Create or update GitHub release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ inputs.github_token }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        artifacts: "build/src/*.a,build/src/*.so"
        allowUpdates: true
        replacesArtifacts: false
        draft: false
        prerelease: false
