inputs:
  tag:
    description: "Artifact tag"
  github_token:
    description: "GitHub token"

runs:
  using: "composite"
  steps:
    - name: Initialize git repository
      shell: bash
      run: git config --global --add safe.directory '*'

    - name: Download build
      uses: actions/download-artifact@v4
      with:
        name: build-${{ inputs.tag }}
        path: build

    - name: Create or update GitHub release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ inputs.github_token }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        artifacts: |
          build/src/libsarus.a
          build/src/libsarus.so
          include/libsarus
        allowUpdates: true
        replacesArtifacts: false
        draft: false
        prerelease: false
