runs:
  using: "composite"
  steps:
    - name: Run build script
      shell: bash
      run: |
        ./build.sh -DBUILD_DIR=$PWD/build

    - name: Run test script
      shell: bash
      run: |
        cd build
        sudo --user docker env "PATH=$PATH" ASAN_OPTIONS=detect_leaks=1 ctest --output-on-failure --exclude-regex AsRoot
        ASAN_OPTIONS=detect_leaks=1 ctest --output-on-failure --tests-regex AsRoot
