FROM ubuntu:22.04

# Install dependencies 
RUN apt update -y && \
    apt install -y \
        sudo \
        build-essential \
        ca-certificates \
        coreutils \
        curl \
        git \
        gpg \
        lsb-release \
        python3 \
        python3-distutils \
        python-is-python3 \
        unzip \
        zip \
        gcc-12 \
        g++-12 \
        kmod \
        autoconf \
        automake \
        squashfs-tools \
        cmake \
        zlib1g \
        wget

# Set up default compilers
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 10
