# Build stage with Spack pre-installed and ready to be used
FROM spack/ubuntu-jammy:develop AS builder

# What we want to install and how we want to install it
# is specified in a manifest file (spack.yaml)
RUN mkdir -p /opt/spack-environment && \
set -o noclobber && ( true \
&&   echo "spack:" \
&&   echo "  specs:" \
&&   echo "  - gcc@12.3.0" \
&&   echo "  - glibc" \
&&   echo "  - kmod" \
&&   echo "  - curl" \
&&   echo "  - git" \
&&   echo "  - autoconf" \
&&   echo "  - automake" \
&&   echo "  - gnupg" \
&&   echo "  - squashfs" \
&&   echo "  - cmake" \
&&   echo "  - zlib-ng" \
&&   echo "  - tini" \
&&   echo "  - boost@1.85+filesystem+regex" \
&&   echo "  - python@3" \
&&   echo "  - py-setuptools" \
&&   echo "  - py-psutil" \
&&   echo "  - py-gcovr" \
&&   echo "  compilers:" \
&&   echo "  - compiler:" \
&&   echo "      spec: gcc@=11.4.0" \
&&   echo "      paths:" \
&&   echo "        cc: /usr/bin/gcc" \
&&   echo "        cxx: /usr/bin/g++" \
&&   echo "        f77: /usr/bin/gfortran" \
&&   echo "        fc: /usr/bin/gfortran" \
&&   echo "      flags: {}" \
&&   echo "      operating_system: ubuntu22.04" \
&&   echo "      target: x86_64" \
&&   echo "      modules: []" \
&&   echo "      environment: {}" \
&&   echo "      extra_rpaths: []" \
&&   echo "  mirrors:" \
&&   echo "    v0.22.1: https://binaries.spack.io/v0.22.1" \
&&   echo "  concretizer:" \
&&   echo "    unify: true" \
&&   echo "  config:" \
&&   echo "    install_tree: /opt/software" \
&&   echo "  view: /opt/views/view" \
) > /opt/spack-environment/spack.yaml

# Install the software, remove unnecessary deps
RUN cd /opt/spack-environment \
    && spack env activate . \
    && spack buildcache keys --install --trust \
    && spack install --fail-fast \
    && spack gc -y

# Install sudo (if needed)
RUN apt update \
    && apt install -y sudo

# Modifications to the environment that are necessary to run
RUN cd /opt/spack-environment && \
    spack env activate --sh -d . > activate.sh

# Bare OS image to run the installed executables
FROM ubuntu:22.04

COPY --from=builder /opt/spack-environment /opt/spack-environment
COPY --from=builder /opt/software /opt/software

# paths.view is a symlink, so copy the parent to avoid dereferencing and duplicating it
COPY --from=builder /opt/views /opt/views

RUN ln -s /opt/views/view /opt/view 

# Switch to the user 'docker'
RUN groupadd docker \
    && useradd -m -g docker docker \
    && echo 'docker:docker' | chpasswd \
    && chown docker:docker /home/docker \
    && echo 'docker ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers 
USER docker 
WORKDIR /home/docker 

# Set up a boot-up environment
# /etc/profile removes *sbin locations from PATH for non-root users
# Modify .bashrc to find /sbin/ldconfig even after test scripts do a
# 'sudo -u docker --login'
RUN echo 'PATH=${PATH}:/usr/local/sbin:/usr/sbin:/sbin' >> .bashrc
RUN echo '.' /opt/spack-environment/activate.sh >> .bashrc 

CMD [ "/bin/bash" ]

