FROM @@FINAL_OS_IMAGE@@

# Install sudo and Spack dependencies 
RUN @@OS_PKG_MANAGER@@ update \
    && @@OS_PKG_MANAGER@@ install -y sudo \
        build-essential ca-certificates coreutils curl \
        environment-modules gfortran git gpg lsb-release \
        python3 python3-distutils python3-venv unzip zip 

# Create the user 'docker'
RUN groupadd docker \
    && useradd -m -g docker docker \
    && echo 'docker:docker' | chpasswd \
    && chown docker:docker /home/docker \
    && echo 'docker ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers 

# Change to the user 'docker'
USER docker 
WORKDIR /home/docker

# Set up Spack
RUN git clone https://github.com/spack/spack.git

# What we want to install and how we want to install it
# is specified in a manifest file (spack.yaml)
RUN mkdir -p spack-environment && \
set -o noclobber && ( true \
@@SPACK_YAML_FILE@@
) > spack-environment/spack.yaml

# Install the software
# Modifications to the environment that are necessary to run
RUN export PATH=$PWD/spack/bin:$PATH \
    && . $PWD/spack/share/spack/setup-env.sh \
    && cd spack-environment \
    && spack env activate . \
    && spack buildcache keys --install --trust \
    && spack install --fail-fast  \
    && spack env activate --sh -d . > activate.sh

#RUN ln -s views/view view 

# Set up a boot-up environment
# /etc/profile removes *sbin locations from PATH for non-root users
# Modify .bashrc to find /sbin/ldconfig even after test scripts do a
# 'sudo -u docker --login'
RUN echo 'PATH=${PATH}:/usr/local/sbin:/usr/sbin:/sbin' >> .bashrc
RUN echo '.' ~/spack-environment/activate.sh >> .bashrc 

CMD [ "/bin/bash" ]
