FROM ubuntu:22.04

# Install dependencies
RUN apt update -y && \
    apt install -y \
        git \
        cmake \
        gcc-12 \
        g++-12 \
        sudo

# Set up default compilers
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 10
