FROM opensuse/leap:15.6

# Install dependencies
RUN zypper update -y && \
    zypper install -y \
        git \
        cmake \
        gcc12 \
        gcc12-c++ \
        sudo

# Set up default compilers
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 10

# Add dummy user
RUN useradd nobody && \
    groupadd nogroup
