name: Default libsarus workflow

on:
  push: {}

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: base/check-format@v1

  check-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: base/check-format@v2
